### ISSUE TITLE
Docs 'coming soon' and how the project maps to AWS

### ISSUE THREAD

**Issue by grempe** [assaf/queue-run#51]
This line in the repo README can probably be updated.

```HTTP APIs, WebSocket, FIFO queues, and (coming) scheduled jobs```

Also, a suggestion. It would be very helpful for people like myself who are evaluating this to have a page to read that talks in some depth about how `queue-run` code gets mapped to AWS constructs behind the scenes. It feels a little 'magical' now unless your project is able to run in isolation from any other AWS services where the integration points are not a big concern.

**Comment by assaf** [comment]
It shouldn't be a mystery how it works. I'll try answering in short form, and if that's any good can add it to the docs:

- QR compiles your project (JS or TS) to ES2020 so it can run on Lambda, with support for ESM+CJS modules
- It packages the entire backend into a single Lambda function and deploys that
- There's a manifest file that lists all the HTTP routes, queues, scheduled jobs, etc
- This manifest allows it to load modules on demand, so to handle an HTTP request, it only needs to load the module for that specific route
- It sets up one API Gateway (regional) to handle HTTPS and WebSocket requests (no multi-region support yet)
- For every file in the `queues` directory, it creates an SQS queue: AWS polls the queue, and forwards messages to the Lambda function (in batches if necessary)
- For every file in the `schedules` directory, it creates one EventBridge rule: AWS triggers the Lambda function based on that schedule
- AWS would run as many instances as allowed by your account, you can control reserved concurrency and provisioned concurrency (https://queue.run/optimizing)

Right now that means that from the outside, a back-end looks like a black-box and you interact with it using HTTP/WebSocket. You can do HTTP request/response, or Webhook notification (where the back-end would use a queue to service it).

So a back-end is currently self-contained. I haven't given enough thought yet how to add other points of integration (SNS? Kinesis?)

**Comment by grempe** [comment]
I think its a good start! Its helpful to understand the current scope of what it does (or doesn't do) behind the scenes.

I think adding it to a section of the intro would be helpful.

Thanks

**Comment by sujal** [comment]
Just bringing the conversation from twitter here - so that list is really helpful. The question I was getting at was really what your last sentence gets to, which is how do you see this evolving over time. Do you want it to remain like a black box, or does it eventually have interfaces for other integrations?

I don't have a solid use case in mind yet, which is why my questions were so wishy-washy. The concrete problem in front of me is that I'm hanging the API services of a subdomain (api.foobar.com), but that domain is already in route53 and so I don't *think* I can use the domain command. The second issue was that I spun up a test app to see what it created, and then realized AWS makes it hard to find everything and clear it, especially if the account is used for other apps. 

Those two things put cloudformation (or whatever orchestration is native to the deploy environment):

* it makes the inventory of what is part of the deployment visible in the stack
* It can be used to provide a stable API rather than pointing at ARNs or IDs that could change depending on how QR manages the infra lifecycles.

Anyway - this is all premature (And I'm sorry I asked it the way I did in hindsight). I really am curious how you would want to handle larger applications or other points of integration - what's top of mind right now.

**Comment by assaf** [comment]
We're merging two different discussions that touch on two common themes:
- Can you tell what happens behind the scenes?
- Does/should this work with other AWS services?
- And if so, how?

I do believe you should be able to tell what happens behind the scenes.

There's my written explanation above, but also warming up to the idea of using CloudFormation as an intermediary step, since it can so the specific configuration of your project. I'm reading about it today to figure out how to make that happen.

In the early releases, everything was managed in memory, you had to implicitly trust the runtime. Then I added a step to generate source code into the build directory so you could inspect that. And then generate a manifest file, for resources used by the framework. So following that logic, would make sense to generate a file describing the AWS deployment.

Should it work with other AWS services? Yes.

The goal is to simplify development. If it only simplifies some services, that's good enough. But if you can only use some services, you run into scenarios where you can't use QueueRun or have to abandon it, which defeats the purpose. So not a black-box.

---

Sidenote: it should work with any nameserver including Route53. Ideally, when using Route53 it should do everything for you, no manual steps. If you're not using Route53 (I'm not), though, there are a couple of manual steps, so that feature I don't think works with CloudFormation. Everything else should.

**Comment by grempe** [comment]
You might also take a look at the AWS CDK which is an abstraction layer on top of CloudFormation. If CDK code can be generated and run this might greatly simplify the job of defining these units of infrastructure.

https://aws.amazon.com/cdk/

**Comment by assaf** [comment]
I think the website has been updated a while back, but now matches with the latest release (0.14) using Cloudformation stack for most things.
